export { default as useDocTitle } from './hooks/doc-title'
export { default as useEvent } from './hooks/event'
export { default as useForceUpdate } from './hooks/force-update'
export { default as useSyncRef } from './hooks/sync-ref'
export { default as useWinSize } from './hooks/win-size'
